# **Tugas 8**

In [95]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [96]:
dataset_url = "https://raw.githubusercontent.com/Dhitaaprilia/datamining/main/credit_score%20(1).csv"
dataset = pd.read_csv(dataset_url)
dataset

,Unnamed: 0,kode_kontrak,pendapatan_setahun_juta,kpr_aktif,durasi_pinjaman_bulan,jumlah_tanggungan,rata_rata_overdue,risk_rating
0,1,AGR-000001,295,YA,48,5,61 - 90 days,4
1,2,AGR-000011,271,YA,36,5,61 - 90 days,4
2,3,AGR-000030,159,TIDAK,12,0,0 - 30 days,1
3,4,AGR-000043,210,YA,12,3,46 - 60 days,3
4,5,AGR-000049,165,TIDAK,36,0,31 - 45 days,2
...,...,...,...,...,...,...,...,...
895,896,AGR-010739,112,YA,48,5,> 90 days,5
896,897,AGR-010744,120,YA,48,2,46 - 60 days,3
897,898,AGR-010758,166,TIDAK,24,2,0 - 30 days,1
898,899,AGR-010775,196,TIDAK,48,0,31 - 45 days,2
899,900,AGR-010790,204,TIDAK,24,2,0 - 30 days,1

In [97]:
data = dataset.drop(columns=['kpr_aktif', 'rata_rata_overdue'])

In [98]:
#Pre processing dengan get dummies panda
data_kpr = dataset[['kpr_aktif']]
data_rata = dataset[['rata_rata_overdue']]
kpr = pd.get_dummies(data_kpr)
rata_rata = pd.get_dummies(data_rata)

In [99]:
dataOlah = pd.concat([kpr,rata_rata],axis=1)

In [100]:
dataHasil = pd.concat([data,dataOlah], axis=1)
dataHasil

,Unnamed: 0,kode_kontrak,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,risk_rating,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,1,AGR-000001,295,48,5,4,0,1,0,0,0,1,0
1,2,AGR-000011,271,36,5,4,0,1,0,0,0,1,0
2,3,AGR-000030,159,12,0,1,1,0,1,0,0,0,0
3,4,AGR-000043,210,12,3,3,0,1,0,0,1,0,0
4,5,AGR-000049,165,36,0,2,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,896,AGR-010739,112,48,5,5,0,1,0,0,0,0,1
896,897,AGR-010744,120,48,2,3,0,1,0,0,1,0,0
897,898,AGR-010758,166,24,2,1,1,0,1,0,0,0,0
898,899,AGR-010775,196,48,0,2,1,0,0,1,0,0,0
899,900,AGR-010790,204,24,2,1,1,0,1,0,0,0,0

**Normalisasi Data**

In [101]:
datakelas = dataHasil['risk_rating']
data = dataHasil.drop(columns=['kode_kontrak','risk_rating'])
data

,Unnamed: 0,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,1,295,48,5,0,1,0,0,0,1,0
1,2,271,36,5,0,1,0,0,0,1,0
2,3,159,12,0,1,0,1,0,0,0,0
3,4,210,12,3,0,1,0,0,1,0,0
4,5,165,36,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
895,896,112,48,5,0,1,0,0,0,0,1
896,897,120,48,2,0,1,0,0,1,0,0
897,898,166,24,2,1,0,1,0,0,0,0
898,899,196,48,0,1,0,0,1,0,0,0
899,900,204,24,2,1,0,1,0,0,0,0

In [102]:
# scale features
scaler = MinMaxScaler()
model =scaler.fit(data)
scaled_data=model.transform(data)
# print scaled features
print(scaled_data)

[[0.         0.97826087 1.         ... 0.         1.         0.        ]
 [0.00111235 0.87391304 0.66666667 ... 0.         1.         0.        ]
 [0.00222469 0.38695652 0.         ... 0.         0.         0.        ]
 ...
 [0.99777531 0.4173913  0.33333333 ... 0.         0.         0.        ]
 [0.99888765 0.54782609 1.         ... 0.         0.         0.        ]
 [1.         0.5826087  0.33333333 ... 0.         0.         0.        ]]

In [103]:
namakolom = data.columns.values
dataMinMax = pd.DataFrame(scaled_data, columns=namakolom)
label = ['Unnamed: 0']
dataMinMax= dataMinMax.drop(columns = label)

In [104]:
dataMinMax

,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,0.978261,1.000000,0.833333,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,0.873913,0.666667,0.833333,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,0.386957,0.000000,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.608696,0.000000,0.500000,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.413043,0.666667,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
895,0.182609,1.000000,0.833333,0.0,1.0,0.0,0.0,0.0,0.0,1.0
896,0.217391,1.000000,0.333333,0.0,1.0,0.0,0.0,1.0,0.0,0.0
897,0.417391,0.333333,0.333333,1.0,0.0,1.0,0.0,0.0,0.0,0.0
898,0.547826,1.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
899,0.582609,0.333333,0.333333,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [105]:
# Z Score atau StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
model = (scaler.fit(data))
data_mean = (scaler.mean_)
scale_data = (scaler.transform(data))
print(scale_data)

[[-1.73012737  2.54041987  1.32217147 ... -0.6912543   2.54950976
  -0.35949218]
 [-1.72627837  2.07740679  0.4439764  ... -0.6912543   2.54950976
  -0.35949218]
 [-1.72242937 -0.08332092 -1.31241375 ... -0.6912543  -0.39223227
  -0.35949218]
 ...
 [ 1.72242937  0.05172456 -0.43421867 ... -0.6912543  -0.39223227
  -0.35949218]
 [ 1.72627837  0.63049091  1.32217147 ... -0.6912543  -0.39223227
  -0.35949218]
 [ 1.73012737  0.78482861 -0.43421867 ... -0.6912543  -0.39223227
  -0.35949218]]

In [106]:
dataZScale = pd.DataFrame(scale_data, columns=data.columns.values)
dataZScale

,Unnamed: 0,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,-1.730127,2.540420,1.322171,1.030621,-0.868554,0.868554,-0.580772,-0.463222,-0.691254,2.549510,-0.359492
1,-1.726278,2.077407,0.443976,1.030621,-0.868554,0.868554,-0.580772,-0.463222,-0.691254,2.549510,-0.359492
2,-1.722429,-0.083321,-1.312414,-1.461477,1.151339,-1.151339,1.721847,-0.463222,-0.691254,-0.392232,-0.359492
3,-1.718580,0.900582,-1.312414,0.033782,-0.868554,0.868554,-0.580772,-0.463222,1.446646,-0.392232,-0.359492
4,-1.714731,0.032432,0.443976,-1.461477,1.151339,-1.151339,-0.580772,2.158791,-0.691254,-0.392232,-0.359492
...,...,...,...,...,...,...,...,...,...,...,...
895,1.714731,-0.990055,1.322171,1.030621,-0.868554,0.868554,-0.580772,-0.463222,-0.691254,-0.392232,2.781702
896,1.718580,-0.835717,1.322171,-0.464638,-0.868554,0.868554,-0.580772,-0.463222,1.446646,-0.392232,-0.359492
897,1.722429,0.051725,-0.434219,-0.464638,1.151339,-1.151339,1.721847,-0.463222,-0.691254,-0.392232,-0.359492
898,1.726278,0.630491,1.322171,-1.461477,1.151339,-1.151339,-0.580772,2.158791,-0.691254,-0.392232,-0.359492
899,1.730127,0.784829,-0.434219,-0.464638,1.151339,-1.151339,1.721847,-0.463222,-0.691254,-0.392232,-0.359492

In [107]:
datakelas = dataHasil['risk_rating']
data = pd.concat([datakelas,dataMinMax],axis=1)
data

,risk_rating,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,kpr_aktif_TIDAK,kpr_aktif_YA,rata_rata_overdue_0 - 30 days,rata_rata_overdue_31 - 45 days,rata_rata_overdue_46 - 60 days,rata_rata_overdue_61 - 90 days,rata_rata_overdue_> 90 days
0,4,0.978261,1.000000,0.833333,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,4,0.873913,0.666667,0.833333,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2,1,0.386957,0.000000,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,3,0.608696,0.000000,0.500000,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,2,0.413043,0.666667,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
895,5,0.182609,1.000000,0.833333,0.0,1.0,0.0,0.0,0.0,0.0,1.0
896,3,0.217391,1.000000,0.333333,0.0,1.0,0.0,0.0,1.0,0.0,0.0
897,1,0.417391,0.333333,0.333333,1.0,0.0,1.0,0.0,0.0,0.0,0.0
898,2,0.547826,1.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
899,1,0.582609,0.333333,0.333333,1.0,0.0,1.0,0.0,0.0,0.0,0.0

Split Data menjadi X dan Y

*   X_train dan X_test 
*   y_test dan y_train

In [108]:
percent_test_data = 0.3
X = data.iloc[:,1:11].values
Y = data.iloc[:,0].values

In [109]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = percent_test_data, random_state=0)

In [110]:
X.shape

(900, 10)

In [111]:
X_train.shape

(630, 10)

**Naive Bayes**

In [112]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [113]:
GaussianNB(priors=None)

GaussianNB()

In [114]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
nvklasifikasi = GaussianNB()
nvklasifikasi = nvklasifikasi.fit(X_train, y_train)

In [115]:
# Predicting the Test set results
y_pred = nvklasifikasi.predict(X_test)
y_pred

array([2, 1, 3, 2, 4, 4, 1, 3, 3, 5, 1, 2, 5, 2, 3, 3, 1, 3, 3, 4, 2, 3,
       3, 1, 5, 3, 3, 3, 3, 3, 2, 3, 5, 3, 1, 4, 4, 4, 4, 2, 4, 1, 1, 2,
       5, 3, 5, 2, 1, 1, 2, 5, 1, 1, 2, 5, 1, 3, 3, 3, 4, 2, 3, 5, 5, 3,
       3, 3, 4, 1, 5, 4, 2, 1, 1, 4, 3, 3, 3, 5, 1, 2, 3, 2, 4, 3, 1, 3,
       2, 1, 2, 3, 2, 2, 3, 1, 2, 5, 5, 1, 1, 1, 3, 1, 5, 4, 3, 5, 2, 2,
       3, 3, 1, 1, 2, 1, 4, 4, 2, 2, 5, 4, 3, 1, 4, 1, 3, 1, 1, 5, 1, 1,
       1, 3, 3, 2, 5, 3, 1, 4, 3, 5, 3, 5, 2, 3, 1, 2, 2, 3, 3, 3, 3, 4,
       5, 3, 3, 4, 3, 1, 2, 1, 1, 1, 2, 1, 3, 1, 4, 2, 1, 1, 4, 2, 2, 1,
       1, 1, 3, 3, 3, 4, 5, 4, 3, 1, 1, 3, 2, 2, 3, 3, 4, 2, 5, 3, 5, 1,
       3, 5, 2, 3, 2, 3, 3, 2, 3, 3, 3, 1, 1, 1, 3, 1, 1, 3, 2, 3, 2, 3,
       3, 1, 1, 1, 1, 5, 1, 3, 2, 1, 4, 1, 5, 4, 4, 3, 3, 3, 3, 3, 2, 3,
       1, 4, 4, 4, 3, 5, 3, 3, 1, 1, 4, 1, 5, 1, 5, 2, 1, 2, 2, 3, 4, 4,
       1, 2, 4, 2, 5, 3])

In [116]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[2, 2],
       [1, 1],
       [3, 3],
       [2, 2],
       [4, 4]])

In [117]:
# Menentukan probabilitas hasil prediksi
nvklasifikasi.predict_proba(X_test)

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.]])

In [118]:
akurasi = round(100 * accuracy_score(y_test, y_pred))
print('Model accuracy score: {0:0.2f}'. format(akurasi))

Model accuracy score: 100.00

In [119]:
# print the scores on training and test set
akurasi_training = round(100* nvklasifikasi.score(X_train, y_train))
akurasi_test = round(100 * nvklasifikasi.score(X_test, y_test) )
print('Training set score: {:.2f}'.format(akurasi_training))
print('Test set score: {:.2f}'.format(akurasi_test))

Training set score: 100.00
Test set score: 100.00

In [120]:
model = GaussianNB()
model.fit(X, Y)
model_pf = GaussianNB()
model_pf.partial_fit(X,Y, np.unique(Y))

GaussianNB()

In [121]:
no_index = 0

In [122]:
# try with value [0,	0,	0,	0,	0,	1,	1,	0.8,	0.9,	0]
result_test_naive_bayes = model_pf.predict([[0,	0,	0,	0,	0,	1,	1,	0.8,	0.9,	0]])[no_index]
print(f"Customer : X Memiliki risk rating {result_test_naive_bayes} Pada metode Gaussian Naive Bayes model")

Customer : X Memiliki risk rating 1 Pada metode Gaussian Naive Bayes model

**KNN**

In [123]:
K=10
knn=KNeighborsClassifier(n_neighbors=K)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)

In [124]:
skor_akurasi = round(100 * accuracy_score(y_test,y_pred))
print("Model accuracy score : {0:0.2f}" . format(skor_akurasi))

Model accuracy score : 100.00

In [125]:
# Custom value to predict
result_test_knn = knn.predict([[0,	0,	0,	0,	0.5,	1,	1,	0.7,	0.2,	0]])
print(f"Customer : X Memiliki risk rating {result_test_knn[no_index]} Pada metode KNN model")

Customer : X Memiliki risk rating 3 Pada metode KNN model

**Decision Tree**

In [126]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [127]:
# prediction
dt.score(X_test, y_test)

1.0

In [128]:
y_pred = dt.predict(X_test)

In [129]:
#Accuracy
akurasi = round(100 * accuracy_score(y_test,y_pred))
print('Model Accuracy Score: {0:0.2f}'.format(akurasi))

Model Accuracy Score: 100.00

In [130]:
# Custom value to predict
result_test_knn = dt.predict([[0,	0,	0,	0.7,	0.6,	1,	1,	0.3,	0.5,	0]])
print(f"Customer : X Memiliki risk rating {result_test_knn[no_index]} Pada metode Decision Tree model")

Customer : X Memiliki risk rating 1 Pada metode Decision Tree model

**Ensemble Learning**

In [131]:
model1 = BaggingClassifier(base_estimator=DecisionTreeClassifier(),n_estimators=10, random_state=0).fit(X_train, y_train)
dt = model1.predict(X_test)
kolom = ['Decision Tree']
dt = pd.DataFrame(dt,columns = kolom)

In [132]:
X_test.shape

(270, 10)

In [133]:
model2 = BaggingClassifier(base_estimator=KNeighborsClassifier(n_neighbors = K),n_estimators=10, random_state=0).fit(X_train, y_train)
knn = model2.predict(X_test)
kolom = ['KNN']
knn = pd.DataFrame(knn,columns = kolom)

In [134]:
model3 = BaggingClassifier(base_estimator=GaussianNB(),n_estimators=10, random_state=0).fit(X_train, y_train)
nb = model3.predict(X_test)
kolom = ['Naive Bayes']
naive_bayes = pd.DataFrame(nb,columns = kolom)

In [135]:
Hasil = pd.concat([dt, knn,naive_bayes], axis=1)
Hasil

     Decision Tree  KNN  Naive Bayes
0                2    2            2
1                1    1            1
2                3    3            3
3                2    2            2
4                4    4            4
..             ...  ...          ...
265              2    2            2
266              4    4            4
267              2    2            2
268              5    5            5
269              3    3            3

[270 rows x 3 columns]

In [136]:
bagging_accuracy1 = round(100 * accuracy_score(y_test, naive_bayes))
bagging_accuracy2 = round(100 * accuracy_score(y_test, dt))
bagging_accuracy3 = round(100 * accuracy_score(y_test, knn))
print('The accuracy of this model is Bagging Naive Bayes {} %.'.format(bagging_accuracy1))
print('The accuracy of this model is Bagging Decision Tree {} %.'.format(bagging_accuracy2))
print('The accuracy of this model is Bagging kNN {} %.'.format(bagging_accuracy3))

The accuracy of this model is Bagging Naive Bayes 100 %.
The accuracy of this model is Bagging Decision Tree 100 %.
The accuracy of this model is Bagging kNN 100 %.

**Stacking**

In [137]:
estimators = [('rf', RandomForestClassifier(n_estimators=10, random_state=42)),
              (('knn',KNeighborsClassifier(n_neighbors=10)))]

In [138]:
clf = StackingClassifier(estimators=estimators, final_estimator= DecisionTreeClassifier())

In [139]:
clf.fit(X_train, y_train)

StackingClassifier(estimators=[('rf',
                                RandomForestClassifier(n_estimators=10,
                                                       random_state=42)),
                               ('knn', KNeighborsClassifier(n_neighbors=10))],
                   final_estimator=DecisionTreeClassifier())

In [140]:
y_predict = clf.predict(X_test)

In [141]:
#Accuracy
akurasi = round(100 * accuracy_score(y_test,y_predict))
print('Model Accuracy Score: {0:0.2f}'.format(akurasi))

Model Accuracy Score: 100.00