# Tugas 1

In [2]:
import pandas as pd
import numpy as np
import math

**Data**

In [6]:
dataset_url="https://raw.githubusercontent.com/Dhitaaprilia/datamining/main/data-rekapitulasi-kejadian-banjir-tahun-2020.csv"
data=pd.read_csv(dataset_url)

In [7]:
data

,bulan,kecamatan,kelurahan,rata_rata_ketinggian_air,lama_genangan,rw_terdampak,kk_terdampak,jiwa_terdampak,korban_meninggal,korban_hilang,korban_luka_berat,korban_luka_ringan,jumlah_jiwa_pengungsi_tertinggi,jumlah_tempat_pengungsian,jumlah_nilai_kerugian
0,1,35,151,10 s.d 350 cm,4 hari,390,22148,83406,19,0,0,0,36445,269,n.a
1,2,42,167,5 s.d 200 cm,1 s.d 2 hari,581,12551,43464,6,0,0,0,13808,119,n.a
2,3,24,46,5 s.d 160 cm,1 s.d 2 hari,104,3057,9687,0,0,0,0,453,14,n.a
3,4,21,50,10 s.d 130 cm,1 s.d 2 hari,106,1059,2966,0,0,0,0,75,2,n.a
4,5,12,23,10 s.d 200 cm,1 s.d 2 hari,47,891,3117,0,0,0,0,213,6,n.a
5,6,9,16,5 s.d 120 cm,1 hari,46,80,320,0,0,0,0,320,7,n.a
6,7,2,2,20 s.d 50 cm,1 hari,4,0,0,0,0,0,0,0,0,n.a
7,8,10,12,10 s.d 80 cm,1 hari,20,0,0,0,0,0,0,0,0,n.a
8,9,16,28,10 s.d 130 cm,1 s.d 2 hari,65,414,1300,0,0,0,0,104,5,n.a
9,10,29,72,10 s.d 180 cm,1 s.d 2 hari,170,1933,6250,0,0,0,0,675,12,n.a
10,11,16,27,10 s.d 60 cm,1 s.d 2 hari,54,0,0,0,0,0,0,0,0,n.a
11,12,7,9,10 s.d 80 cm,1 hari,18,250,827,0,0,0,0,0,0,n.a

In [8]:
def diss(x,y) :
  i=10
  j=0
  for col in ["bulan","kecamatan","kelurahan","rata_rata_ketinggian_air","lama_genangan","rw_terdampak","kk_terdampak","jiwa_terdampak","korban_meninggal","korban_hilang","korban_luka_berat","korban_luka_ringan","jumlah_jiwa_pengungsi_tertinggi","jumlah_tempat_pengungsian","jumlah_nilai_kerugian"] :
    if data[col][x]==data[col][y] :
      j+=1
    return (i-j)/i

In [9]:
print(diss(1,1))

0.9

In [10]:
data.describe()

,bulan,kecamatan,kelurahan,rw_terdampak,kk_terdampak,jiwa_terdampak,korban_meninggal,korban_hilang,korban_luka_berat,korban_luka_ringan,jumlah_jiwa_pengungsi_tertinggi,jumlah_tempat_pengungsian
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.0,12.0,12.0,12.000000,12.000000
mean,6.500000,18.583333,50.250000,133.750000,3531.916667,12611.416667,2.083333,0.0,0.0,0.0,4341.083333,36.166667
std,3.605551,12.033728,54.536268,175.330921,6833.112408,25389.682606,5.599648,0.0,0.0,0.0,10844.285797,80.498259
min,1.000000,2.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
25%,3.750000,9.750000,15.000000,39.500000,60.000000,240.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000
50%,6.500000,16.000000,27.500000,59.500000,652.500000,2133.000000,0.000000,0.0,0.0,0.0,158.500000,5.500000
75%,9.250000,25.250000,55.500000,122.000000,2214.000000,7109.250000,0.000000,0.0,0.0,0.0,508.500000,12.500000
max,12.000000,42.000000,167.000000,581.000000,22148.000000,83406.000000,19.000000,0.0,0.0,0.0,36445.000000,269.000000

**Normalisasi Rating**

In [11]:
std_kec=12.033728
mean_kec=18.583333
for col1 in ["kecamatan"] :
  data1=data[col1]
  hasil1=(data1-mean_kec)/std_kec
  print(hasil1)

0     1.364221
1     1.945920
2     0.450124
3     0.200824
4    -0.547073
5    -0.796373
6    -1.378071
7    -0.713273
8    -0.214674
9     0.865623
10   -0.214674
11   -0.962572
Name: kecamatan, dtype: float64

**Normalisasi Metascore**

In [12]:
std_kel=54.536268
mean_kel=50.250000
for col2 in ["kelurahan"] :
  data2=data[col2]
  hasil2=(data2-mean_kel)/std_kel
  print(hasil2)

0     1.847394
1     2.140777
2    -0.077930
3    -0.004584
4    -0.499667
5    -0.628022
6    -0.884732
7    -0.701368
8    -0.407985
9     0.398817
10   -0.426322
11   -0.756377
Name: kelurahan, dtype: float64

**Menghitung Jarak Data Numerik Dengan Cara Euclidean**

In [13]:
def num_data(a,b,c) :
  result=0
  for col in [hasil1,hasil2] :
    result=math.pow(abs(col[a]-col[b]),c)
  return result**(1/c)

In [14]:
print(num_data(1,2,2))
print(num_data(1,3,2))
print(num_data(1,4,2))

2.218707007967615
2.1453613217538097
2.6404447036969967

**Similarity**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [15]:
print("Jarak d(1,2) =",diss(1,2)+num_data(1,2,2))

Jarak d(1,2) = 3.218707007967615

In [16]:
print("Jarak d(1,3) =",diss(1,3)+num_data(1,3,3))

Jarak d(1,3) = 3.1453613217538097

In [17]:
print("Jarak d(1,4) =",diss(1,4)+num_data(1,4,4))

Jarak d(1,4) = 3.6404447036969967