# Tugas 2 (Diskritisasi)

In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
dataset1_url="https://raw.githubusercontent.com/venky14/Machine-Learning-with-Iris-Dataset/master/Iris.csv"
dt=pd.read_csv(dataset1_url)

In [4]:
dt.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [5]:
from sklearn.preprocessing import KBinsDiscretizer

In [6]:
sepalLength=dt.SepalLengthCm
sepalWidth=dt.SepalWidthCm
petalLength=dt.PetalLengthCm
petalWidth=dt.PetalWidthCm
spesies=dt.Species

In [7]:
spL=sepalLength.values.reshape(-1,1)
spW=sepalWidth.values.reshape(-1,1)
ptL=petalLength.values.reshape(-1,1)
ptW=petalWidth.values.reshape(-1,1)
sp=spesies.values.reshape(-1,1)

In [8]:
est=KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [9]:
est.fit(spL)
est.fit(spW)
est.fit(ptL)
est.fit(ptW)

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [10]:
KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

KBinsDiscretizer(encode='ordinal', n_bins=4, strategy='uniform')

In [11]:
KBinsDiscretizer(...)

KBinsDiscretizer(n_bins=Ellipsis)

In [12]:
KBinsDiscretizer(n_bins=Ellipsis)

KBinsDiscretizer(n_bins=Ellipsis)

In [13]:
aa=est.transform(spL)
ab=est.transform(spW)
ac=est.transform(ptL)
ad=est.transform(ptW)

In [14]:
b1={'SepalLengthCm':aa}
b2={'SepalLengthCm':ab}
b3={'SepalLengthCm':ac}
b4={'SepalLengthCm':ad}

In [15]:
c1=pd.DataFrame(aa,columns=['SepalLengthCm'])
c2=pd.DataFrame(ab,columns=['SepalWidthCm'])
c3=pd.DataFrame(ac,columns=['PetalLengthCm'])
c4=pd.DataFrame(ad,columns=['PetalWidthCm'])
c5=pd.DataFrame(sp,columns=['Species'])

In [16]:
datalist=[c1, c2, c3, c4, c5]
pd.concat(datalist, axis=1)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              3.0           3.0            2.0           0.0     Iris-setosa
1              3.0           3.0            2.0           0.0     Iris-setosa
2              3.0           3.0            2.0           0.0     Iris-setosa
3              3.0           3.0            2.0           0.0     Iris-setosa
4              3.0           3.0            2.0           0.0     Iris-setosa
..             ...           ...            ...           ...             ...
145            3.0           3.0            3.0           3.0  Iris-virginica
146            3.0           3.0            3.0           3.0  Iris-virginica
147            3.0           3.0            3.0           3.0  Iris-virginica
148            3.0           3.0            3.0           3.0  Iris-virginica
149            3.0           3.0            3.0           2.0  Iris-virginica

[150 rows x 5 columns]